# -*- coding: utf-8 -*-
"""Vaccine_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7Z8Cfix_bqSDwEOZYTj4766wGEAWlmz
"""

# Vaccination Data - Exploratory Data Analysis (EDA)
# =====================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Set visualization style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

class VaccinationEDA:
    """
    Comprehensive EDA for vaccination data analysis
    """

    def __init__(self, data_path='/content/'):
        self.data_path = data_path
        self.coverage_df = None
        self.incidence_df = None
        self.cases_df = None
        self.intro_df = None
        self.schedule_df = None

    def load_cleaned_data(self):
        """Load all cleaned datasets"""
        print("Loading cleaned datasets...")
        self.coverage_df = pd.read_excel(f'{self.data_path}/coverage-data.xlsx')
        self.incidence_df = pd.read_excel(f'{self.data_path}/incidence-rate-data.xlsx')
        self.cases_df = pd.read_excel(f'{self.data_path}/reported-cases-data.xlsx')
        self.intro_df = pd.read_excel(f'{self.data_path}/vaccine-introduction-data.xlsx')
        self.schedule_df = pd.read_excel(f'{self.data_path}/vaccine-schedule-data.xlsx')

        # Convert all column names to lowercase for consistency
        self.coverage_df.columns = self.coverage_df.columns.str.lower()
        self.incidence_df.columns = self.incidence_df.columns.str.lower()
        self.cases_df.columns = self.cases_df.columns.str.lower()
        self.intro_df.columns = self.intro_df.columns.str.lower()
        self.schedule_df.columns = self.schedule_df.columns.str.lower()

        print("✓ All datasets loaded\n")

    def dataset_overview(self):
        """Generate comprehensive dataset overview"""
        print("="*70)
        print("DATASET OVERVIEW")
        print("="*70)

        datasets = {
            'Coverage': self.coverage_df,
            'Incidence': self.incidence_df,
            'Cases': self.cases_df,
            'Introduction': self.intro_df,
            'Schedule': self.schedule_df
        }

        for name, df in datasets.items():
            print(f"\n{name} Dataset:")
            print(f"Shape: {df.shape}")
            print(f"Memory usage: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
            if 'year' in df.columns:
                print(f"Date range: {df['year'].min()} - {df['year'].max()}")
            else:
                print("Date range: 'year' column not found or not applicable.")

            if 'code' in df.columns:
                print(f"Unique countries: {df['code'].nunique()}")
            elif 'iso_3_code' in df.columns:
                print(f"Unique countries: {df['iso_3_code'].nunique()}")
            else:
                print("Unique countries: Country identifier column ('code' or 'iso_3_code') not found.")

    def analyze_vaccination_coverage(self):
        """Analyze vaccination coverage trends"""
        print("\n" + "="*70)
        print("VACCINATION COVERAGE ANALYSIS")
        print("="*70)

        df = self.coverage_df
        if 'year' not in df.columns:
            print("Skipping Vaccination Coverage Analysis: 'year' column not found in coverage data.")
            return
        if 'coverage' not in df.columns:
            print("Skipping Vaccination Coverage Analysis: 'coverage' column not found in coverage data.")
            return
        if 'name' not in df.columns:
            print("Skipping Vaccination Coverage Analysis: 'name' column not found in coverage data.")
            return
        if 'antigen_description' not in df.columns:
            print("Skipping Vaccination Coverage Analysis: 'antigen_description' column not found in coverage data.")
            return

        # Global coverage trends
        coverage_by_year = df.groupby('year')['coverage'].agg(['mean', 'median', 'std'])
        print("\nGlobal Coverage Trends (2015-2024):")
        print(coverage_by_year.tail(10))

        # Top performing countries
        recent_coverage = df[df['year'] >= 2020].groupby('name')['coverage'].mean()
        print("\nTop 10 Countries by Vaccination Coverage (2020+):")
        print(recent_coverage.nlargest(10))

        # Low coverage regions
        print("\nBottom 10 Countries (Need Intervention):")
        print(recent_coverage.nsmallest(10))

        # Vaccine-specific coverage
        vaccine_coverage = df.groupby('antigen_description')['coverage'].agg(['mean', 'count'])
        print("\nCoverage by Vaccine Type:")
        print(vaccine_coverage.sort_values('mean', ascending=False).head(10))

    def analyze_disease_incidence(self):
        """Analyze disease incidence patterns"""
        print("\n" + "="*70)
        print("DISEASE INCIDENCE ANALYSIS")
        print("="*70)

        df = self.incidence_df
        if 'year' not in df.columns:
            print("Skipping Disease Incidence Analysis: 'year' column not found in incidence data.")
            return
        if 'disease_description' not in df.columns:
            print("Skipping Disease Incidence Analysis: 'disease_description' column not found in incidence data.")
            return
        if 'incidence_rate' not in df.columns:
            print("Skipping Disease Incidence Analysis: 'incidence_rate' column not found in incidence data.")
            return

        # Disease trends over time
        disease_trends = df.groupby(['year', 'disease_description'])['incidence_rate'].mean().unstack()
        print("\nDisease Incidence Trends (Recent Years):")
        print(disease_trends.tail())

        # High incidence diseases
        high_incidence = df.groupby('disease_description')['incidence_rate'].agg(['mean', 'max', 'count'])
        print("\nDiseases with Highest Average Incidence:")
        print(high_incidence.sort_values('mean', ascending=False).head(10))

    def analyze_vaccination_impact(self):
        """Analyze correlation between vaccination and disease reduction"""
        print("\n" + "="*70)
        print("VACCINATION IMPACT ANALYSIS")
        print("="*70)

        if 'code' not in self.coverage_df.columns or 'year' not in self.coverage_df.columns or \
           'code' not in self.cases_df.columns or 'year' not in self.cases_df.columns:
            print("Skipping Vaccination Impact Analysis: 'code' or 'year' column(s) not found in coverage or cases data.")
            return

        # Merge coverage and cases data
        coverage_agg = self.coverage_df.groupby(['code', 'year', 'antigen_description'])['coverage'].mean().reset_index()
        cases_agg = self.cases_df.groupby(['code', 'year', 'disease_description'])['cases'].sum().reset_index()

        # Example: Measles vaccination vs cases
        measles_vax = coverage_agg[coverage_agg['antigen_description'].str.contains('Measles', case=False, na=False)]
        measles_cases = cases_agg[cases_agg['disease_description'].str.contains('Measles', case=False, na=False)]

        merged = pd.merge(measles_vax, measles_cases, on=['code', 'year'], how='inner')

        if len(merged) > 0:
            correlation = merged['coverage'].corr(merged['cases'])
            print(f"\nCorrelation between Measles vaccination and cases: {correlation:.4f}")
            print("(Negative correlation indicates vaccination reduces cases)")
        else:
            print("No common data found for Measles vaccination and cases to calculate correlation.")

    def regional_disparities(self):
        """Analyze regional vaccination disparities"""
        print("\n" + "="*70)
        print("REGIONAL DISPARITY ANALYSIS")
        print("="*70)

        if 'who_region' not in self.intro_df.columns or 'code' not in self.coverage_df.columns or 'year' not in self.coverage_df.columns:
            print("Skipping Regional Disparity Analysis: 'who_region' in intro data or 'code'/'year' in coverage data not found.")
            return

        region_coverage = pd.merge(
            self.coverage_df[['code', 'year', 'coverage']],
            self.intro_df[['iso_3_code', 'who_region']].drop_duplicates(),
            left_on='code',
            right_on='iso_3_code',
            how='left'
        )

        region_stats = region_coverage.groupby('who_region')['coverage'].agg(['mean', 'std', 'min', 'max'])
        print("\nVaccination Coverage by WHO Region:")
        print(region_stats.sort_values('mean', ascending=False))

    def temporal_analysis(self):
        """Analyze temporal patterns in vaccination"""
        print("\n" + "="*70)
        print("TEMPORAL PATTERN ANALYSIS")
        print("="*70)

        df = self.coverage_df
        if 'year' not in df.columns:
            print("Skipping Temporal Pattern Analysis: 'year' column not found in coverage data.")
            return

        # Year-over-year growth
        yearly_coverage = df.groupby('year')['coverage'].mean()
        yoy_growth = yearly_coverage.pct_change() * 100

        print("\nYear-over-Year Coverage Growth (%):")
        print(yoy_growth.tail(10))

        # Identify acceleration/deceleration periods
        recent_trend = yoy_growth.tail(5).mean()
        print(f"\nAverage growth trend (last 5 years): {recent_trend:.2f}%")

    def vaccine_introduction_analysis(self):
        """Analyze vaccine introduction patterns"""
        print("\n" + "="*70)
        print("VACCINE INTRODUCTION ANALYSIS")
        print("="*70)

        df = self.intro_df
        if 'year' not in df.columns:
            print("Skipping Vaccine Introduction Analysis: 'year' column not found in introduction data.")
            return

        # Introduction timeline
        intro_by_year = df[df['intro'].str.contains('Yes', case=False, na=False)].groupby('year').size()
        print("\nVaccine Introductions Over Time:")
        print(intro_by_year.tail(10))

        # Regional introduction patterns
        if 'who_region' in df.columns:
            region_intro = df[df['intro'].str.contains('Yes', case=False, na=False)].groupby('who_region').size()
            print("\nVaccine Introductions by Region:")
            print(region_intro.sort_values(ascending=False))
        else:
            print("Skipping Regional Introduction Patterns: 'who_region' column not found in introduction data.")

    def generate_statistical_summary(self):
        """Generate comprehensive statistical summary"""
        print("\n" + "="*70)
        print("STATISTICAL SUMMARY")
        print("="*70)

        print("\nCoverage Statistics:")
        if 'coverage' in self.coverage_df.columns:
            print(self.coverage_df['coverage'].describe())
        else:
            print("'coverage' column not found in Coverage data.")

        print("\nIncidence Rate Statistics:")
        if 'incidence_rate' in self.incidence_df.columns:
            print(self.incidence_df['incidence_rate'].describe())
        else:
            print("'incidence_rate' column not found in Incidence data.")

        print("\nReported Cases Statistics:")
        if 'cases' in self.cases_df.columns:
            print(self.cases_df['cases'].describe())
        else:
            print("'cases' column not found in Cases data.")

    def identify_key_insights(self):
        """Generate key insights and recommendations"""
        print("\n" + "="*70)
        print("KEY INSIGHTS & RECOMMENDATIONS")
        print("="*70)

        insights = []

        # Low coverage countries
        if 'year' in self.coverage_df.columns and 'name' in self.coverage_df.columns:
            recent_data = self.coverage_df[self.coverage_df['year'] >= 2020]
            low_coverage = recent_data.groupby('name')['coverage'].mean()
            low_coverage_countries = low_coverage[low_coverage < 50].index.tolist()

            if low_coverage_countries:
                insights.append(f"• {len(low_coverage_countries)} countries have <50% coverage - require immediate intervention")
        else:
            insights.append("Skipping low coverage countries analysis: 'year' or 'name' column not found in coverage data.")

        # High disease burden
        if 'disease_description' in self.cases_df.columns:
            high_cases = self.cases_df.groupby('disease_description')['cases'].sum()
            top_disease = high_cases.idxmax()
            insights.append(f"• {top_disease} has highest case burden - prioritize vaccination efforts")
        else:
            insights.append("Skipping high disease burden analysis: 'disease_description' column not found in cases data.")

        # Coverage improvement
        if 'year' in self.coverage_df.columns:
            coverage_change = self.coverage_df.groupby('year')['coverage'].mean()
            if len(coverage_change) >= 5: # Need at least 5 years for a 5-year comparison
                recent_improvement = coverage_change.iloc[-1] - coverage_change.iloc[-5]
                if recent_improvement > 0:
                    insights.append(f"• Global coverage improved by {recent_improvement:.1f}% over last 5 years")
                else:
                    insights.append(f"• WARNING: Coverage declined by {abs(recent_improvement):.1f}% - urgent action needed")
            else:
                insights.append("Skipping coverage improvement analysis: Not enough years for 5-year comparison.")
        else:
            insights.append("Skipping coverage improvement analysis: 'year' column not found in coverage data.")

        if insights:
            print("\n" + "\n".join(insights))
        else:
            print("No key insights could be generated due to missing data columns.")

    def run_complete_eda(self):
        """Execute complete EDA pipeline"""
        print("="*70)
        print("VACCINATION DATA - EXPLORATORY DATA ANALYSIS")
        print("="*70)

        self.load_cleaned_data()
        self.dataset_overview()
        self.analyze_vaccination_coverage()
        self.analyze_disease_incidence()
        self.analyze_vaccination_impact()
        self.regional_disparities()
        self.temporal_analysis()
        self.vaccine_introduction_analysis()
        self.generate_statistical_summary()
        self.identify_key_insights()

        print("\n" + "="*70)
        print("✓ EDA COMPLETED SUCCESSFULLY")
        print("="*70)

# Usage
if __name__ == "__main__":
    eda = VaccinationEDA('/content/')
    eda.run_complete_eda()

    # Generate visualizations
    print("\nGenerating visualizations...")

    # Create output directory
    import os
    os.makedirs('visualizations', exist_ok=True)

    # Visualization 1: Coverage trends
    if 'year' in eda.coverage_df.columns and 'coverage' in eda.coverage_df.columns:
        plt.figure(figsize=(12, 6))
        yearly_coverage = eda.coverage_df.groupby('year')['coverage'].mean()
        plt.plot(yearly_coverage.index, yearly_coverage.values, marker='o', linewidth=2)
        plt.title('Global Vaccination Coverage Trend', fontsize=16, fontweight='bold')
        plt.xlabel('Year', fontsize=12)
        plt.ylabel('Average Coverage (%)', fontsize=12)
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig('visualizations/coverage_trend.png', dpi=300)
        print("✓ Coverage trend chart saved")
    else:
        print("Skipping Coverage trend chart: 'year' or 'coverage' column not found in coverage data.")

    # Visualization 2: Top vaccines by coverage
    if 'antigen_description' in eda.coverage_df.columns and 'coverage' in eda.coverage_df.columns:
        plt.figure(figsize=(12, 8))
        top_vaccines = eda.coverage_df.groupby('antigen_description')['coverage'].mean().nlargest(15)
        top_vaccines.plot(kind='barh', color='steelblue')
        plt.title('Top 15 Vaccines by Average Coverage', fontsize=16, fontweight='bold')
        plt.xlabel('Average Coverage (%)', fontsize=12)
        plt.ylabel('Vaccine', fontsize=12)
        plt.tight_layout()
        plt.savefig('visualizations/top_vaccines.png', dpi=300)
        print("✓ Top vaccines chart saved")
    else:
        print("Skipping Top vaccines chart: 'antigen_description' or 'coverage' column not found in coverage data.")

    print("\n✓ All visualizations attempted.")

"""### **9. Additional Visualizations:**

Let's create some additional visualizations to further explore the regional disparities and disease incidence trends identified in the EDA.
"""

# Visualization 3: Regional Vaccination Coverage Disparities (Heatmap)

# Re-calculate region_stats as it was a local variable in the EDA class method
if 'code' in eda.coverage_df.columns and 'year' in eda.coverage_df.columns and \
   'iso_3_code' in eda.intro_df.columns and 'who_region' in eda.intro_df.columns and \
   'coverage' in eda.coverage_df.columns:
    region_coverage = pd.merge(
        eda.coverage_df[['code', 'year', 'coverage']],
        eda.intro_df[['iso_3_code', 'who_region']].drop_duplicates(),
        left_on='code',
        right_on='iso_3_code',
        how='left'
    )
    # Drop rows where 'who_region' is NaN due to merge issues
    region_coverage = region_coverage.dropna(subset=['who_region'])

    # Aggregate for heatmap (e.g., mean coverage by region and year)
    regional_coverage_pivot = region_coverage.pivot_table(index='who_region', columns='year', values='coverage', aggfunc='mean')

    plt.figure(figsize=(14, 8))
    sns.heatmap(regional_coverage_pivot, cmap='viridis', fmt=".1f", linewidths=.5, linecolor='black')
    plt.title('Average Vaccination Coverage by WHO Region Over Time', fontsize=16, fontweight='bold')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('WHO Region', fontsize=12)
    plt.tight_layout()
    plt.savefig('visualizations/regional_coverage_heatmap.png', dpi=300)
    print("✓ Regional coverage heatmap saved")
else:
    print("Skipping Regional coverage heatmap: Required columns not found.")

# Visualization 4: Disease Incidence Trends (Heatmap)

# Re-calculate disease_trends as it was a local variable in the EDA class method
if 'year' in eda.incidence_df.columns and 'disease_description' in eda.incidence_df.columns and \
   'incidence_rate' in eda.incidence_df.columns:
    disease_trends_pivot = eda.incidence_df.groupby(['year', 'disease_description'])['incidence_rate'].mean().unstack()

    plt.figure(figsize=(16, 10))
    sns.heatmap(disease_trends_pivot.loc[2010:], cmap='YlOrRd', linewidths=.5, linecolor='black') # Focus on more recent years
    plt.title('Average Disease Incidence Rate by Disease Over Time (2010 Onwards)', fontsize=16, fontweight='bold')
    plt.xlabel('Disease', fontsize=12)
    plt.ylabel('Year', fontsize=12)
    plt.tight_layout()
    plt.savefig('visualizations/disease_incidence_heatmap.png', dpi=300)
    print("✓ Disease incidence heatmap saved")
else:
    print("Skipping Disease incidence heatmap: Required columns not found.")

# Visualization 5: Top 10 Low-Coverage Countries (Bar Chart)

if 'year' in eda.coverage_df.columns and 'name' in eda.coverage_df.columns and 'coverage' in eda.coverage_df.columns:
    recent_data = eda.coverage_df[eda.coverage_df['year'] >= 2020]
    low_coverage = recent_data.groupby('name')['coverage'].mean()
    bottom_10_countries = low_coverage.nsmallest(10)

    plt.figure(figsize=(12, 7))
    sns.barplot(x=bottom_10_countries.values, y=bottom_10_countries.index, palette='Reds_d')
    plt.title('Top 10 Countries with Lowest Average Vaccination Coverage (2020+)', fontsize=16, fontweight='bold')
    plt.xlabel('Average Coverage (%)', fontsize=12)
    plt.ylabel('Country/Region', fontsize=12)
    plt.tight_layout()
    plt.savefig('visualizations/low_coverage_countries_bar_chart.png', dpi=300)
    print("✓ Low-coverage countries bar chart saved")
else:
    print("Skipping Low-coverage countries bar chart: Required columns not found.")

print("\n--- Column Names for Each DataFrame ---")

if eda.coverage_df is not None:
    print("\nCoverage DataFrame Columns:")
    print(eda.coverage_df.columns.tolist())

if eda.incidence_df is not None:
    print("\nIncidence DataFrame Columns:")
    print(eda.incidence_df.columns.tolist())

if eda.cases_df is not None:
    print("\nCases DataFrame Columns:")
    print(eda.cases_df.columns.tolist())

if eda.intro_df is not None:
    print("\nIntroduction DataFrame Columns:")
    print(eda.intro_df.columns.tolist())

if eda.schedule_df is not None:
    print("\nSchedule DataFrame Columns:")
    print(eda.schedule_df.columns.tolist())

import os

# Check for 'cleaned_data' directory
cleaned_data_dir = '/content/cleaned_data'
print(f"Checking directory: {cleaned_data_dir}")
if os.path.exists(cleaned_data_dir) and os.path.isdir(cleaned_data_dir):
    print(f"  '{cleaned_data_dir}' exists.")
    print(f"  Contents: {os.listdir(cleaned_data_dir)}")
else:
    print(f"  '{cleaned_data_dir}' does NOT exist.")

print("\nChecking for expected Excel data files in '/content/':")
excel_files = [
    'coverage-data.xlsx',
    'incidence-rate-data.xlsx',
    'reported-cases-data.xlsx',
    'vaccine-introduction-data.xlsx',
    'vaccine-schedule-data.xlsx'
]

for file_name in excel_files:
    file_path = os.path.join('/content/', file_name)
    if os.path.exists(file_path):
        print(f"  ✓ '{file_name}' found.")
    else:
        print(f"  ✗ '{file_name}' NOT found.")